config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => redirect('/events')

  resources :event_users_linkings

  resources :event_details

  resources :user_profiles

  resources :events

end

app/models/event_detail.rb
class EventDetail < ActiveRecord::Base
  has_many :events
  
end

app/controllers/event_details_controller.rb
class EventDetailsController < ApplicationController
  before_action :set_event_detail, only: [:show, :edit, :update, :destroy]

  # GET /event_details
  # GET /event_details.json
  def index
    @event_details = EventDetail.all
  end

  # GET /event_details/1
  # GET /event_details/1.json
  def show
  end

  # GET /event_details/new
  def new
    @event_detail = EventDetail.new
  end

  # GET /event_details/1/edit
  def edit
  end

  # POST /event_details
  # POST /event_details.json
  def create
    @event_detail = EventDetail.new(event_detail_params)

    respond_to do |format|
      if @event_detail.save
        format.html { redirect_to @event_detail, notice: 'Event detail was successfully created.' }
        format.json { render :show, status: :created, location: @event_detail }
      else
        format.html { render :new }
        format.json { render json: @event_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_details/1
  # PATCH/PUT /event_details/1.json
  def update
    respond_to do |format|
      if @event_detail.update(event_detail_params)
        format.html { redirect_to @event_detail, notice: 'Event detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_detail }
      else
        format.html { render :edit }
        format.json { render json: @event_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_details/1
  # DELETE /event_details/1.json
  def destroy
    @event_detail.destroy
    respond_to do |format|
      format.html { redirect_to event_details_url, notice: 'Event detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_detail
      @event_detail = EventDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_detail_params
      params.require(:event_detail).permit(:name, :description, :picture, :venue, :max_participants)
    end
end

app/helpers/event_details_helper.rb
module EventDetailsHelper
end

app/views/event_details/_form.html.slim
= form_for @event_detail do |f|
  - if @event_detail.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event_detail.errors.count, "error")} prohibited this event_detail from being saved:"
      ul
        - @event_detail.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :picture
    = f.text_field :picture
  
  .actions = f.submit 'Save'

app/views/event_details/edit.html.slim
h1 Editing event_detail

== render 'form'

= link_to 'Show', @event_detail
'|
= link_to 'Back', event_details_path

app/views/event_details/index.html.slim
h1 Listing event_details

table
  thead
    tr
      th Name
      th Description
      th Picture
      th
      th
      th

  tbody
    - @event_details.each do |event_detail|
      tr
        td = event_detail.name
        td = event_detail.description
        td = event_detail.picture
        td = link_to 'Show', event_detail
        td = link_to 'Edit', edit_event_detail_path(event_detail)
        td = link_to 'Destroy', event_detail, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Event detail', new_event_detail_path

app/views/event_details/new.html.slim
h1 New event_detail

== render 'form'

= link_to 'Back', event_details_path

app/views/event_details/show.html.slim
p
  strong Name:
  = @event_detail.name
p
  strong Description:
  = @event_detail.description
p
  strong Picture:
  = @event_detail.picture

= link_to 'Edit', edit_event_detail_path(@event_detail)

= link_to 'Back', event_details_path