config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => redirect('/events')

  resources :event_users_linkings

  resources :event_details

  resources :user_profiles

  resources :events

end

app/models/event_users_linking.rb
class EventUsersLinking < ActiveRecord::Base
end

app/controllers/event_users_linkings_controller.rb
class EventDetailsLinkingsController < ApplicationController
  before_action :set_event_users_linking, only: [:show, :edit, :update, :destroy]

  # GET /event_users_linkings
  # GET /event_users_linkings.json
  def index
    @event_users_linkings = EventDetailsLinking.all
  end

  # GET /event_users_linkings/1
  # GET /event_users_linkings/1.json
  def show
  end

  # GET /event_users_linkings/new
  def new
    @event_users_linking = EventDetailsLinking.new
  end

  # GET /event_users_linkings/1/edit
  def edit
  end

  # POST /event_users_linkings
  # POST /event_users_linkings.json
  def create
    @event_users_linking = EventDetailsLinking.new(event_users_linking_params)

    respond_to do |format|
      if @event_users_linking.save
        format.html { redirect_to @event_users_linking, notice: 'Event details linking was successfully created.' }
        format.json { render :show, status: :created, location: @event_users_linking }
      else
        format.html { render :new }
        format.json { render json: @event_users_linking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_users_linkings/1
  # PATCH/PUT /event_users_linkings/1.json
  def update
    respond_to do |format|
      if @event_users_linking.update(event_users_linking_params)
        format.html { redirect_to @event_users_linking, notice: 'Event details linking was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_users_linking }
      else
        format.html { render :edit }
        format.json { render json: @event_users_linking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_users_linkings/1
  # DELETE /event_users_linkings/1.json
  def destroy
    @event_users_linking.destroy
    respond_to do |format|
      format.html { redirect_to event_users_linkings_url, notice: 'Event details linking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_users_linking
      @event_users_linking = EventDetailsLinking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_users_linking_params
      params.require(:event_users_linking).permit(:user_id, :integer, :event_detail_id, :integer)
    end
end

app/helpers/event_users_linkings_helper.rb
module EventUsersLinkingsHelper
end

app/views/event_users_linkings/_form.html.slim
= form_for @event_details_linking do |f|
  - if @event_details_linking.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event_details_linking.errors.count, "error")} prohibited this event_details_linking from being saved:"
      ul
        - @event_details_linking.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :event_id
    = f.text_field :event_detail_id
  .field
    = f.label :venue
    = f.text_field :venue
  .field
    = f.label :max_participants
    = f.text_field :max_participants
  .actions = f.submit 'Save'

app/views/event_users_linkings/edit.html.slim
h1 Editing event_details_linking

== render 'form'

= link_to 'Show', @event_details_linking
'|
= link_to 'Back', event_details_linkings_path

app/views/event_users_linkings/index.html.slim
h1 Listing event_users_linkings

table
  thead
    tr
      th User
      th Event
      th Venue
      th Max participants
      th
      th
      th

  tbody
    - @event_users_linkings.each do |event_users_linking|
      tr
        td = event_users_linking.user_id
        td = event_users_linking.event_id
        td = event_users_linking.venue
        td = event_users_linking.max_participants
        td = link_to 'Show', event_users_linking
        td = link_to 'Edit', edit_event_users_linking_path(event_users_linking)
        td = link_to 'Destroy', event_users_linking, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Event users linking', new_event_users_linking_path

app/views/event_users_linkings/new.html.slim
h1 New event_users_linking

== render 'form'

= link_to 'Back', event_details_linkings_path

app/views/event_users_linkings/show.html.slim
p
  strong User:
  = @event_users_linking.user_id
p
  strong Event detail:
  = @event_users_linking.event_detail_id
p
  strong Venue:
  = @event_users_linking.venue
p
  strong Max participants:
  = @event_users_linking.max_participants

= link_to 'Edit', edit_event_details_linking_path(@event_details_linking)
= link_to 'Back', event_details_linkings_path