config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => redirect('/events')

  resources :event_users_linkings

  resources :event_details

  resources :user_profiles

  resources :events

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:first_name, :string,last_name, :string,user_name, :string,mobile, :string)
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :string,last_name %><br>
    <%= f.text_field :string,last_name %>
  </div>
  <div class="field">
    <%= f.label :string,user_name %><br>
    <%= f.text_field :string,user_name %>
  </div>
  <div class="field">
    <%= f.label :string,mobile %><br>
    <%= f.text_field :string,mobile %>
  </div>
  <div class="field">
    <%= f.label :string,email %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/_form.html.slim
= form_for(@user_profile) do |f|
  - if @user_profile.errors.any?
    #error_explanation
      h2
        = pluralize(@user_profile.errors.count, "error")
        | prohibited this user_profile from being saved:
      ul
        - @user_profile.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :first_name
    br
      = f.text_field :first_name
  .field
    = f.label :string,last_name
    br
      = f.text_field :string,last_name
  .field
    = f.label :string,user_name
    br
      = f.text_field :string,user_name
  .field
    = f.label :string,mobile
    br
      = f.text_field :string,mobile
  .field
    = f.label :string,email
    br
      = f.text_field :string
  .actions
    = f.submit

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/edit.html.slim
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>String,last name</th>
      <th>String,user name</th>
      <th>String,mobile</th>
      <th>String,email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.first_name %></td>
        <td><%= user_profile.string,last_name %></td>
        <td><%= user_profile.string,user_name %></td>
        <td><%= user_profile.string,mobile %></td>
        <td><%= user_profile.string,email %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/index.html.slim
h1 Listing user_profiles
table
  thead
    tr
      th First name
      th String,last name
      th String,user name
      th String,mobile
      th String,email
      th colspan="3" 
  tbody
    - @user_profiles.each do |user_profile|
      tr
        td= user_profile.first_name
        td= user_profile.string,last_name
        td= user_profile.string,user_name
        td= user_profile.string,mobile
        td= user_profile.string,email
        td= link_to 'Show', user_profile
        td= link_to 'Edit', edit_user_profile_path(user_profile)
        td= link_to 'Destroy', user_profile, method: :delete, data:   confirm: 'Are you sure?'  
br
  = link_to 'New User profile', new_user_profile_path

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/new.html.slim
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user_profile.first_name %>
</p>

<p>
  <strong>String,last name:</strong>
  <%= @user_profile.string,last_name %>
</p>

<p>
  <strong>String,user name:</strong>
  <%= @user_profile.string,user_name %>
</p>

<p>
  <strong>String,mobile:</strong>
  <%= @user_profile.string,mobile %>
</p>

<p>
  <strong>String:</strong>
  <%= @user_profile.string,email %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.slim
p#notice= notice
p
  strong First name:
  = @user_profile.first_name
p
  strong String,last name:
  = @user_profile.string,last_name
p
  strong String,user name:
  = @user_profile.string,user_name
p
  strong String,mobile:
  = @user_profile.string,mobile
p
  strong String:
  = @user_profile.string,email
= link_to 'Edit', edit_user_profile_path(@user_profile)
= link_to 'Back', user_profiles_path